name: NodeJS with Webpack

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Serve Build (optional)
      run: |
        npm install -g serve
        serve -s public
